import Head from "next/head";
import { useState } from "react";
import swal from "sweetalert";

export default function Home() {
  const [inputValue, setInputValue] = useState("");

  const submitHandler = (e) => {
    e.preventDefault();
    if (inputValue === "Either you run the day or the day runs you") {
      window.open("https://musical-starship-a748983c.netlify.app", "_blank");
    } else if (inputValue === "Either you run the day or the day runs you") {
      window.open("https://nbc.com", "_blank");
    } else {
      swal("Thank	you	for	submitting", inputValue, "success");
    }
  };

  return (
    <div>
      <Head>
        <title>Saeed Feeder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Join our newsletter</h1>
        <p>Enter your email for weekly updates</p>
        <form onSubmit={submitHandler}>
          <div className="input-container">
            <input
              placeholder="Enter your choice"
              maxLength={80}
              onChange={(e) => setInputValue(e.target.value)}
            />
            <button type="submit">Submit</button>
          </div>
        </form>
      </main>
    </div>
  );
}
